### ISSUE TITLE
Add Docker Documentation

### ISSUE THREAD

**Issue by chadfawcett** [chadfawcett/mailhound#33]
I have added a Dockerfile for easy deployment with Docker. The README should show a simple example of running the image. A docker-compose example would also be great.

**Comment by xRahul** [comment]
Hey @chadfawcett 

I have experience with both the docker and docker-compose. I'll take this one!

**Comment by thiagobbt** [comment]
@xRahul Sorry, I had not seen your comment. I created steps for running with regular docker, not docker-compose.

**Comment by chadfawcett** [comment]
Hi @xRahul! @thiagobbt got the docker one done but I would really like it if you could write the docker-compose portion. As I pointed out in #34 I forgot to mention that I published the image to Docker Hub. There is no build required, just point to [chadfawcett/mailhound](https://hub.docker.com/r/chadfawcett/mailhound/).

**Comment by xRahul** [comment]
Sure, I'll add `docker-compose.yml` file and update the readme accordingly

**Comment by xRahul** [comment]
PR created- https://github.com/chadfawcett/mailhound/pull/35
